config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  devise_for :users
  match 'facebookusers/sign_out', to: 'facebookusers#sign_out', via: 'get', as: 'signout'
  match 'facebookusers/start', to: 'facebookusers#start', via: 'get', as: 'facebookusers/start/'
  match 'facebookusers/callback', to: 'facebookusers#callback', via: 'get', as: 'facebookusers/callback/'
  match 'facebookusers/invite_friends', to: 'facebookusers#invite_friends', via: 'post', as: 'invite'
  

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  field :identifier, type: String, default: ""
  field :access_token, type: String, default: ""
  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
  validate :email_verify
  
  def email_verify
    begin
      EmailVerifier.check(self.email)
    rescue Exception => e
      logger.error("Email Error #{e.message}")
      errors.add(:email, "email is not valid")

    end
  end
  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

end

app/controllers/facebookusers_controller.rb
class FacebookusersController < ApplicationController
 def start
   redirect_to client.authorization.authorize_url(:redirect_uri => "http://#{request.env['HTTP_HOST']}/facebookusers/callback/" ,
      :client_id => '514601985316733',:scope => 'email')
  end

  def callback
    @access_token = client.authorization.process_callback(params[:code], :redirect_uri => "http://#{request.env['HTTP_HOST']}/facebookusers/callback/")
    session[:access_token] = @access_token
    @fb_user = client.selection.me.info!
    user = User.find_or_create_by(email: @fb_user.email)
    session[:email] = @fb_user.email
    user.update_attributes(identifier: @fb_user.id,access_token: @access_token)
    user.save(validate: false)
    redirect_to root_url
  end
  def sign_out
    session[:access_token] = nil
    session[:email] = nil
    redirect_to root_url
  end

  def invite_friend
  end
  
  protected

  def client
    @client ||= FBGraph::Client.new(:client_id => '514601985316733',:secret_id => '32247c021fd7e86b5daa1c2fca6e6f19' ,
      :token => session[:access_token])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/facebookusers/callback.html.erb
hello world

app/views/facebookusers/invite_friends.js.erb
 FB.ui({method: 'apprequests',message: 'hello testing' });

app/views/home/index.html.erb
Hello <%= session[:email] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mongodemofb" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
<div id="fb-root"></div>
<script src="http://connect.facebook.net/en_US/all.js"></script>
    <script>
      FB.init({
        appId: "514601985316733",
        cookie: true,
        xfbml: true,
        oauth: true
      });
    (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/all.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Mongodemofb</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
        

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <% if current_user.present? %>
                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign in", new_user_session_path %><br /></li>
                <li> <%= link_to "Sign up", new_user_registration_path %></li>         
              <% end %>
              <% if session[:access_token].present? %>
                <p><%= link_to "signout", signout_path, :method => :get %></p>
                 <p><%= link_to "Invite Friends", invite_path, :method => :post, :remote => true %></p>
              <% else %>
                <p><%= link_to "Facebook Connect", facebookusers_start_path, :method => :get %></p>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
         
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

  </body>
</html>

app/views/users/shared/_links.erb
<% if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end %>

<% if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<% if devise_mapping.omniauthable? %>
  <% resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>